In [2]:
from numpy import array
A = array([[1,2,3],[1,2,3],[1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [3]:
from numpy import empty
A = empty([3,3])
A

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.84973725e-321],
       [1.17982966e-311, 1.17982966e-311, 1.18167149e-311]])

In [4]:
from numpy import zeros
A = zeros([3,5])
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
from numpy import ones
A = ones([5, 5])
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:

# lower
from numpy import tril
lower = tril(M)
# upper
from numpy import triu
upper = triu(M)

NameError: name 'M' is not defined

In [9]:
from numpy import identity
I = identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])